#!/bin/bash/env bash 
if [$# -eq 4 ]; then
	IP=$1
	PATH_TO_SSH_KEY=$2
	USERNAME=$3
	PATH_TO_FILE=$4
	scp -i $PATH_TO_FILE -o StrictHostKeyChecking=no $IP $USERNAME@PATH_TO_SSH_KEY:
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
