#!/usr/bin/env bash


#configure Nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "s@oldtext@$newtext@" /etc/nginx/sites-available/default
sudo service nginx restart
