#!/usr/bin/env bash
#Script for 1-8 same phrase 9 diffrent phrase

x=1; while [ $x -le 10 ] 

do
       

    if
            [ $x -eq  4 ];

then
	echo "bad luck" 

   

    elif
            [ $x -eq 8 ];

then
       echo "good luck"

else 
	echo "Best School"
    fi
((x++))


done
