#!/usr/bin/env bash
configure HAProxy load balancer

sudo apt update
sudo apt install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
fefig="\nfrontend www\n\tbind *:80\n\tdefault_backend nginx_pool\n"
echo -e "$fefig" | sudo tee -a /etc/haproxy/haproxy.cfg
befig1="backend nginx_pool\n\tbalance roundrobin\n\tserver web-01 34.228.81.157:80 check"
befig2="server web-02 34.204.10.91:80 check"
echo -e "$befig1\n\t$befig2" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
